### ISSUE TITLE
Add an option to move the date and time to the end of the taskbar.

### ISSUE THREAD

**Issue by Sultech** [linux-is-awesome/gnome_extension_rocketbar#10]
When enabling this extension I believe the default place for the time should be right at the end.

**Comment by ChepKun** [comment]
I would suggest to use [Just Perfection](https://extensions.gnome.org/extension/3843/just-perfection) to move it to the end. I don't see a reason to implement it while we have Just Perfection that does the job well

**Comment by Sultech** [comment]
Not everyone would want to install just perfection to just change the where the date and time is positioned, I feel like an extension that modifies the panel should be able to move the date and time in the panel
