### ISSUE TITLE
Unity dbus interface support for notifications

### ISSUE THREAD

**Issue by Rend0e** [linux-is-awesome/gnome_extension_rocketbar#15]
Hi, I was wondering whether this extension supports notification badges counters similar to dash to panel, it doesn't seem to show any badges for the apps geary (email client) and telegram so far that works on dash to panel. 
![Screenshot from 2022-08-05 16-28-38](https://user-images.githubusercontent.com/20853575/183026954-e49d6e6c-d7a1-46e9-b44f-29bf4bd1a6dc.png)
^rocketbar (left), dash to panel (right) geary shows notification badge while rocketbar doesn't.

**Comment by ChepKun** [comment]
Rocketbar uses the standard Message Tray functionality to handle notifications. So you probably need to enable native notifications in Telegram.
![image](https://user-images.githubusercontent.com/5459599/183042560-0e47e1df-48fc-40d9-b398-42bd5bc2f90d.png)
![image](https://user-images.githubusercontent.com/5459599/183041549-8c6138d0-a0d2-45bb-b56e-602b1f77c8b8.png)

Not sure about Geary, but for Thunderbird it works fine.
As far as I know Dash to Panel uses a Unity dbus interface to show the badges, I was unable to push any notifications to the interface, so I went with the standard solution. I will take a look if I can implement the interface as well to cover more cases.

**Comment by ChepKun** [comment]
Implemented
