### ISSUE TITLE
Minimize app with multiple windows after last

### ISSUE THREAD

**Issue by Rend0e** [linux-is-awesome/gnome_extension_rocketbar#17]
Hello, could the app be minimized after cycling to the last window and have the blacklight 'blink' (clicking the icon should make the backlight darker/brighter like a flash for a split second) to indicate it's being clicked:

https://user-images.githubusercontent.com/20853575/183034993-ca9cc5e0-bb79-4cc4-99ee-22c3f99ed544.mp4

Also, could apps with multiple windows show all its windows previews when hovering over its icon? 

https://user-images.githubusercontent.com/20853575/183038507-f3d20448-9edd-46f9-a1ae-70f00112d59f.mp4

**Comment by ChepKun** [comment]
Hey!
1. Minimized after cycling to the last window - I have an idea to implement a long press action for app buttons to minimize/unminimize all windows instead of changing cycling behavior, what do you think about it?
2. windows previews - probably after implementing other features I have on my list

**Comment by Rend0e** [comment]
> Hey!
> 
>     1. Minimized after cycling to the last window - I have an idea to implement a long press action for app buttons to minimize/unminimize all windows instead of changing cycling behavior, what do you think about it?
> 
>     2. windows previews - probably after implementing other features I have on my list

I changed my workflow to match more of default gnome intended ( no minimize, simply display apps per workspace) so I don't really need these features anymore! 

Though for 1, I prefer the original (maybe make a toggle for minimize on last cycle to make it optional) since long presses feels more like drag and drop (to rearrange apps icons).

**Comment by ChepKun** [comment]
Implemented

**Comment by ChepKun** [comment]
Implemented
