### ISSUE TITLE
App buttons notification badge stopped working after a OS maintenance update.

### ISSUE THREAD

**Issue by in4matix** [linux-is-awesome/gnome_extension_rocketbar#37]
Displaying of notification badges on top of app buttons worked perfectly fine until I updated Ubuntu 22.04 this morning. I update my system whenever updates become available, so I am not sure which component broke this... I have checked RocketBar settings, all good. Any tips on how to troubleshoot to fix ?

**Comment by ChepKun** [comment]
@in4matix I suspect Ubuntu 22.04 uses Gnome 44, right? So the extension version is 8, please correct me if I'm wrong

**Comment by in4matix** [comment]
Ubuntu 22.04 uses Gnome 42.9. But a subsequent update seems to have fixed the issue and notification badges are working normally gain.
