### ISSUE TITLE
Scroll on taskbar to change workspace

### ISSUE THREAD

**Issue by Sultech** [linux-is-awesome/gnome_extension_rocketbar#8]
Would it be possible to add an option to scroll on the taskbar to change workspace. Here is an extension that does this
https://extensions.gnome.org//extension/701/top-panel-workspace-scroll/

**Comment by ChepKun** [comment]
Instead of changing sound volume, right?

**Comment by Sultech** [comment]
Yes

**Comment by ChepKun** [comment]
On my todo list for now

**Comment by ChepKun** [comment]
Implemented

**Comment by ChepKun** [comment]
Implemented
