### ISSUE TITLE
Add an option to change the size of the panel and position

### ISSUE THREAD

**Issue by Sultech** [linux-is-awesome/gnome_extension_rocketbar#9]
Add an option in the settings to resize the taskbar and have the ability to put it to the bottom of the screen, I'm not sure how you managed to move the taskbar to the bottom of the screen I could not find an option.

**Comment by ChepKun** [comment]
I would suggest to use [Just Perfection](https://extensions.gnome.org/extension/3843/just-perfection) to move it to the end. I don't see a reason to implement it while we have Just Perfection that does the job well.

**Comment by ChepKun** [comment]
I get your point, but at the same time I believe it's not possible to meet everyone's expectations. Either way, I appreciate the feedback!
